version: "3.7"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: app
    entrypoint: ["/usr/src/app/entrypoint.dev.sh"]
    volumes:
      - "./server/:/usr/src/app"
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    build:
      context: ./server/app/db
      dockerfile: Dockerfile
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - "./client/:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_LOCATION_SERVICE_URL=${REACT_APP_LOCATION_SERVICE_URL}
    depends_on:
      - app
    command: ["npm", "start"]
