version: "3.7"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - "./server/:/usr/src/app"
    ports:
      - 5002:5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=app.config.ProductionConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres

  postgres:
    build:
      context: ./server/app/db
      dockerfile: Dockerfile
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
