version: "3.7"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - "./server/:/usr/src/app"
    ports:
      - 5003:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
    depends_on:
      - database

  database:
    build:
      context: ./server/app/db
      dockerfile: Dockerfile
    container_name: db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
